version: '3'

services: 
  postgres:
    image: postgres:10
    environment: 
      POSTGRES_PASSWORD: postgres_password
      
  redis:
    image: redis:5-alpine
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/opt/app
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379  
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres_password
      PGPORT: 5432
  
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/opt/app
  
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/opt/app
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379  